Add all files
fed1k/Portfolio pull request #1
Opened 2022-01-06 17:55 UTC by fed1k

Add html,css,needed images.

2022-01-06 21:39 UTC, mmsesay requested changes
I removed comments. Follow the comments from the second reviewer.

2022-01-06 21:39 UTC, mmsesay commented on README.md
> +every time.
- [ ] You did well adding a readme. A readme is essential for you as a developer to know how to document your project by writing a README because It is the first file a person will see when they encounter your project, so it should be fairly brief but detailed.
Currently, the readme only holds commands for linters.  Please use the [Microverse readme teamplate](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) to give your project a brief description.

2022-01-06 21:39 UTC, mmsesay commented on app.html
> +    </header>
- [ ] Kudos in implementing these codes. It will be more clearer if the header handles the toolbar and the headline section be in a section on its own. Bundling the nav and the section inside the header is not a good practice.

Please break it down using the example below as a guide of the structure.

```
<body>
    <header>
       <a> // logo anchor tag goes here </a>
        <nav> // menu icon goes here </nav>
    </header>

    <section class="section"> // you content goes here </section>
</body>
```

2022-01-06 21:39 UTC, mmsesay commented on app.html
> +            <!--<img src="image-geometry_1.png" alt="shapes">-->
- [ ] [OPTIONAL] Comments are good. They get some explanation of what you did. But I will suggest you remove unused comments to keep your codebase clean.

2022-01-06 21:39 UTC, mmsesay commented on app.css
> +    font-family: Playfair Display;
- [ ][OPTIONAL] The correct font is been used here but it's not effective on your design. `Playfair Display` is an external font. Because of this reason, you need to use a generic font like `Serif` alongside it. If you don't you will eventually get a CSS linter error like this: `font-family-no-missing-generic-family-keyword`

Please apply something like `font-family: 'Playfair Display', Serif;`
Verify that the correct font displays correctly on the web.

2022-01-06 21:39 UTC, mmsesay commented on app.css
> +    font-family: Poppins;
- [ ] [OPTIONAL] Just like I suggested for the font family above, you might need to add `Serif` here as well and for all sections where you used external fonts.

2022-01-06 21:39 UTC, mmsesay commented on app.css
> +}
- [ ] The main title is missing the correct font given in your chosen design. The `Playfair Display` should be used.
Please remember `Playfair Display` is an external font. Therefore, you may need to pass a generic font famil like `Serif`. If you don't use a `Serif` you might end up getting stylint error `font-family-no-missing-generic-family-keyword`

Consider something like: `font-family: Playfair Display, Serif` might help.

- [ ] The `Poppins` font is also needed for the `p` tag. Remember that `Poppins` is also an external font

2022-01-06 21:39 UTC, mmsesay commented on app.html
> +            <img src="image_geometry_1.png" alt="">
- [ ] You did load the image and placed it correctly as guided in the design. This image is supposed to be a background image. I will suggest you set it in your CSS instead of using the `img` tag.

2022-01-06 21:39 UTC, mmsesay commented on app.html
> +            <img src="image_geometry_2.png" alt="">
- [ ] - [ ] You did load the image and placed it correctly as guided in the design. This image is supposed to be a background image. I will suggest you set it in your CSS instead of using the `img` tag.

2022-01-06 21:59 UTC, enkog requested changes
Hi @fed1k 👋 , 

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlight
✅ Linters are set up correctly.
✅ Correct Github flow.
✅ Stuck to Figma design
✅ Code is clean and easy to understand

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Renaming your `app.html` file to `index.html`. This is because when a connection is made to a website without specifying a specific file in the URL, most servers return a default page. This page is known as the "landing page" and most servers will provide by default a file named "index.html".

- [ ] Creating an `images` folder and including all your images there so you have a one-stop for all images and a cleaner code.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-06 21:59 UTC, enkog commented on README.md
> +   - **Remember** that `.github` folder starts with a dot.
- [ ] I recommend that you make your README.md file more detailed and specific to your project. Consider using this [template](https://github.com/microverseinc/readme-template) already provided by Microverse. This is to ensure that visitors to this repository understand what the project is about right away.

2022-01-06 21:59 UTC, enkog commented on app.html
> +        </section>
- [ ] Please separate this section from the `header` tag. This is because according to the project requirement, the `toolbar` should be in a `header` tag while the `headline` is a section after this header.
![Capture](https://user-images.githubusercontent.com/26796167/148456770-9acfd10c-7070-4a1b-829e-972b9e593597.PNG)

2022-01-07 14:34 UTC, Kingstalux requested changes
Hi @fed1k , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
- [ ] Your README file is not related to your project at all, so you'll have to correct that and you'll be good to go. Use this [template](https://github.com/microverseinc/readme-template) provided by the previous reviewer and edit it using your information and information about the project.  A good README file makes your project look more professional so let's get right on that.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-01-07 15:55 UTC, VICTOR-CHUKWU approved these changes
Hi @fed1k  👏 , 
# STATUS: APPROVED! 🥇 💯 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-07 15:55 UTC, VICTOR-CHUKWU commented on README.md
> +  Allamurotov Firdavs
- [ ] OPTIONAL  As already mentioned by previous reviewers I recommend that you make your README.md file more detailed and specific to your project. Consider using this [template](https://github.com/microverseinc/readme-template) already provided by Microverse. This is to ensure that visitors to this repository understand what the project is about right away.

2022-01-07 15:57 UTC, merged